### ISSUE TITLE
[False Positive] Spyware.DiscordStealer.Generic

### ISSUE THREAD

**Issue by BradleyDS2** [DiamondMiner88/AmongUsCheat#1]
![image](https://user-images.githubusercontent.com/2174921/96566447-4fda2400-1311-11eb-86ca-5cce7181ce25.png)

**Comment by Koavu** [comment]
lel token logger

**Comment by DiamondMiner88** [comment]
If you would like you can read the source code and see there's nothing shady.
What anticheat are you using, I would like to know what triggered it.

**Comment by Koavu** [comment]
Bruh i legit see it on the source dumbass

Op wo 21 okt. 2020 om 17:50 schreef Diamond <notifications@github.com>:

**Comment by DiamondMiner88** [comment]
Show where
I have no knowledge of any malicious code in my repo

**Comment by BradleyDS2** [comment]
The provided precompiled exe is flagged by Malwarebytes when attempting to execute it.

**Comment by DiamondMiner88** [comment]
Not really much I can do about about that
I checked and indeed malwarebytes flags my executable.
If you want to compile from source go ahead, I am not hiding anything
You came here for an among us hack, here it is
I checked and didn't see anything sus from shlifedev's code
